# Generated by Django 5.2.5 on 2025-08-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50, unique=True)),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('margin', models.CharField(blank=True, max_length=50, null=True)),
                ('ground', models.CharField(max_length=100)),
                ('match_date', models.DateField()),
            ],
        ),
    ]
