# Generated by Django 5.2.5 on 2025-08-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('role', models.CharField(max_length=50)),
                ('batting_style', models.CharField(blank=True, max_length=50, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=50, null=True)),
                ('od_matches', models.IntegerField(default=0)),
                ('domestic_team', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
