# Generated by Django 5.2.5 on 2025-08-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bowling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs', models.FloatField()),
                ('maidens', models.IntegerField(default=0)),
                ('runs_conceded', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('economy', models.FloatField()),
                ('dot_balls', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('wides', models.IntegerField(default=0)),
                ('no_balls', models.IntegerField(default=0)),
                ('bowling_position', models.IntegerField()),
                ('bowling_team', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.player')),
            ],
        ),
    ]
