# Generated by Django 5.2.5 on 2025-08-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_bowling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.IntegerField()),
                ('balls', models.IntegerField()),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('dismissal', models.CharField(blank=True, max_length=100, null=True)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(blank=True, null=True)),
                ('batting_position', models.IntegerField(blank=True, null=True)),
                ('batting_team', models.CharField(max_length=100)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.player')),
            ],
            options={
                'unique_together': {('match', 'player')},
            },
        ),
    ]
